DROP DATABASE tempus;

CREATE DATABASE tempus;

CREATE TABLE categories (
  cat_id        INTEGER PRIMARY KEY AUTO_INCREMENT,
  name          VARCHAR(100) NOT NULL,
  colour        VARCHAR(100) NOT NULL 
  /* rgba(255,255,255,1.0) */
);

CREATE TABLE todo_item (
  task_id       INTEGER PRIMARY KEY AUTO_INCREMENT,
  task          VARCHAR(100) NOT NULL,
  s_day         DATE,
  start_time    TIME,
  end_time      TIME,
  details       VARCHAR(1000),
  priority      ENUM("urgent", "high", "medium", "low"),
  cat_id        INTEGER, 
  CONSTRAINT FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
);

CREATE TABLE routine_events (
  event_id      INTEGER AUTO_INCREMENT,
  event         VARCHAR(100) NOT NULL,
  recurs        ENUM("daily", "weekly", "fortnightly", "monthly", "quarterly", "biannual", "yearly") NOT NULL,
  s_day         DATE,
  start_time    TIME NOT NULL,
  end_time      TIME NOT NULL,
  place         VARCHAR(100),
  attendees     VARCHAR(300),
  details       VARCHAR(1000),
  url           VARCHAR(200),
  cat_id        INTEGER NOT NULL, 
  PRIMARY KEY (event_id),
  CONSTRAINT FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
);

CREATE TABLE work_hol (
  num           INT AUTO_INCREMENT,
  start_date    DATE,
  end_date      DATE,
  work_days     BOOLEAN,
  hol_days      BOOLEAN,
  PRIMARY KEY (num)
);

CREATE TABLE special_events (
  num           INT AUTO_INCREMENT,
  event         VARCHAR(100) NOT NULL,
  s_day         DATE,
  yearly        BOOLEAN,
  attendees     VARCHAR(300),
  details       VARCHAR(1000),
  PRIMARY KEY (num)
);

CREATE TABLE bank_holidays (
  num           INT AUTO_INCREMENT,
  title         VARCHAR(100) NOT NULL,
  shops_open    VARCHAR(200) NOT NULL,
  holiday       DATE,
  PRIMARY KEY (num)
);

-- MySQL Script generated by MySQL Workbench
-- Tue 25 Aug 2015 14:23:21 BST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tempus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tempus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tempus` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tempus` ;

-- -----------------------------------------------------
-- Table `tempus`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tempus`.`categories` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `colour` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tempus`.`task_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tempus`.`task_item` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `task` VARCHAR(100) NOT NULL,
  `s_day` DATE NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `details` VARCHAR(1000) NULL,
  `priority` ENUM('urgent', 'high', 'medium', 'low') NULL DEFAULT 'medium',
  `cat_id` INT NOT NULL,
  PRIMARY KEY (`task_id`),
  INDEX `cat_id_idx` (`cat_id` ASC),
  CONSTRAINT `cat_id`
    FOREIGN KEY (`cat_id`)
    REFERENCES `tempus`.`categories` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tempus`.`routine_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tempus`.`routine_events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `event` VARCHAR(100) NOT NULL,
  `recurs` ENUM('daily', 'weekly', 'fortnightly', 'lunar', 'monthly', 'bimonthly', 'quarterly', 'yearly') NOT NULL DEFAULT 'daily',
  `s_day` DATE NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `place` VARCHAR(100) NULL,
  `attendees` VARCHAR(100) NULL,
  `details` VARCHAR(1000) NULL,
  `url` VARCHAR(300) NULL,
  `cat_id` INT NOT NULL,
  PRIMARY KEY (`event_id`),
  INDEX `cat_id_idx` (`cat_id` ASC),
  CONSTRAINT `cat_id`
    FOREIGN KEY (`cat_id`)
    REFERENCES `tempus`.`categories` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tempus`.`recurrences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tempus`.`recurrences` (
  `rec_id` INT NOT NULL AUTO_INCREMENT,
  `next_date` DATE NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`rec_id`),
  INDEX `event_id_idx` (`event_id` ASC),
  CONSTRAINT `event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `tempus`.`routine_events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tempus`.`work_hol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tempus`.`work_hol` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `work` TINYINT(1) NULL DEFAULT 0,
  `holiday` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tempus`.`anniversary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tempus`.`anniversary` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `event` VARCHAR(100) NOT NULL,
  `s_day` DATE NOT NULL,
  `birthday` TINYINT(1) NULL DEFAULT 0,
  `place` VARCHAR(100) NULL,
  `details` VARCHAR(1000) NULL,
  PRIMARY KEY (`num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tempus`.`bank_holidays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tempus`.`bank_holidays` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `shops_open` TINYINT(1) NOT NULL DEFAULT 1,
  `hol_date` DATE NOT NULL,
  PRIMARY KEY (`num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tempus`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tempus`.`notes` (
  `note_id` INT NOT NULL AUTO_INCREMENT,
  `s_day` DATE NOT NULL,
  `content` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`note_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

